# gen 1 crime


new_data <- readr::read_csv('data/df_crime_gen1/df_crime_gen1.csv',
                            col_types = cols())

names(new_data) <- c('R0000100',
                     'R0173600',
                     'R0214700',
                     'R0214800',
                     'R0304600',
                     'R0304900',
                     'R0305000',
                     'R0305100',
                     'R0305200',
                     'R0305300',
                     'R0305400',
                     'R0305500',
                     'R0305600',
                     'R0305900',
                     'R0306000',
                     'R0306100',
                     'R0306200',
                     'R0306300',
                     'R0306400',
                     'R0306500',
                     'R0306700',
                     'R0306800',
                     'R0306900',
                     'R0307000',
                     'R0307100',
                     'R0307200',
                     'R0307300',
                     'R0307400',
                     'R0307500',
                     'R0307600',
                     'R0307700',
                     'R0307800',
                     'R0307900',
                     'R0308000',
                     'R0308100',
                     'R0308200',
                     'R0308300',
                     'R0308400',
                     'R0308500',
                     'R0308600',
                     'R0308700',
                     'R0308800',
                     'R0308900',
                     'R0309000',
                     'R0309100',
                     'R0309200',
                     'R0309300',
                     'R0309400',
                     'R0309500',
                     'R0309600',
                     'R0309800',
                     'R0309900',
                     'R0310000',
                     'R0310100',
                     'R0310200',
                     'R0310300',
                     'R0310400',
                     'R0310410',
                     'R0310600',
                     'R0310700',
                     'R0310800',
                     'R0310810',
                     'R0310900',
                     'R0311000',
                     'R0311100',
                     'R0311200',
                     'R0311210',
                     'R0406310',
                     'R0618810',
                     'R0898510',
                     'R1144710',
                     'R1519910',
                     'R1890300',
                     'R2257400',
                     'R2444600',
                     'R2870100',
                     'R3073900',
                     'R3400500',
                     'R3655900',
                     'R4006400',
                     'R4417500',
                     'R4980800',
                     'R5080500',
                     'R5165800',
                     'R6478500',
                     'R7006300',
                     'R7703500',
                     'R8495900',
                     'T0987500',
                     'T2209800',
                     'T3107600',
                     'T4112100',
                     'T5022300',
                     'T5770600')


# Handle missing values

new_data[new_data == -1] = NA  # Refused
new_data[new_data == -2] = NA  # Dont know
new_data[new_data == -3] = NA  # Invalid missing
new_data[new_data == -4] = NA  # Valid missing
new_data[new_data == -5] = NA  # Non-interview


# If there are values not categorized they will be represented as NA

vallabels = function(data) {
  data$R0173600 <- factor(data$R0173600,
                          levels=c(1.0,2.0,3.0,4.0,5.0,6.0,7.0,8.0,9.0,10.0,11.0,12.0,13.0,14.0,15.0,16.0,17.0,18.0,19.0,20.0),
                          labels=c("CROSS MALE WHITE",
                                   "CROSS MALE WH. POOR",
                                   "CROSS MALE BLACK",
                                   "CROSS MALE HISPANIC",
                                   "CROSS FEMALE WHITE",
                                   "CROSS FEMALE WH POOR",
                                   "CROSS FEMALE BLACK",
                                   "CROSS FEMALE HISPANIC",
                                   "SUP MALE WH POOR",
                                   "SUP MALE BLACK",
                                   "SUP MALE HISPANIC",
                                   "SUP FEM WH POOR",
                                   "SUP FEMALE BLACK",
                                   "SUP FEMALE HISPANIC",
                                   "MIL MALE WHITE",
                                   "MIL MALE BLACK",
                                   "MIL MALE HISPANIC",
                                   "MIL FEMALE WHITE",
                                   "MIL FEMALE BLACK",
                                   "MIL FEMALE HISPANIC"))
  #  data$R0214700 <- factor(data$R0214700,
  #    levels=c(1.0,2.0,3.0),
  #    labels=c("HISPANIC",
  #      "BLACK",
  #      "NON-BLACK, NON-HISPANIC"))
  #  data$R0214800 <- factor(data$R0214800,
  #    levels=c(1.0,2.0),
  #    labels=c("MALE",
  #      "FEMALE"))
  # data$R0304600 <- factor(data$R0304600,
  #   levels=c(0.0,1.0,2.0,3.0,4.0,5.0,6.0),
  #   labels=c("NEVER",
  #     "ONCE",
  #     "TWICE",
  #     "3-5 TIMES",
  #     "6-10 TIMES",
  #     "11-50 TIMES",
  #     "MORE THAN 50 TIMES"))
  # data$R0304900 <- factor(data$R0304900,
  #   levels=c(0.0,1.0,2.0,3.0,4.0,5.0,6.0),
  #   labels=c("NEVER",
  #     "ONCE",
  #     "TWICE",
  #     "3-5 TIMES",
  #     "6-10 TIMES",
  #     "11-50 TIMES",
  #     "MORE THAN 50 TIMES"))
  # data$R0305000 <- factor(data$R0305000,
  #   levels=c(0.0,1.0,2.0,3.0,4.0,5.0,6.0),
  #   labels=c("NEVER",
  #     "ONCE",
  #     "TWICE",
  #     "3-5 TIMES",
  #     "6-10 TIMES",
  #     "11-50 TIMES",
  #     "MORE THAN 50 TIMES"))
  # data$R0305100 <- factor(data$R0305100,
  #   levels=c(0.0,1.0,2.0,3.0,4.0,5.0,6.0),
  #   labels=c("NEVER",
  #     "ONCE",
  #     "TWICE",
  #     "3-5 TIMES",
  #     "6-10 TIMES",
  #     "11-50 TIMES",
  #     "MORE THAN 50 TIMES"))
  # data$R0305200 <- factor(data$R0305200,
  #   levels=c(0.0,1.0,2.0,3.0,4.0,5.0,6.0),
  #   labels=c("NEVER",
  #     "ONCE",
  #     "TWICE",
  #     "3-5 TIMES",
  #     "6-10 TIMES",
  #     "11-50 TIMES",
  #     "MORE THAN 50 TIMES"))
  # data$R0305300 <- factor(data$R0305300,
  #   levels=c(0.0,1.0,2.0,3.0,4.0,5.0,6.0),
  #   labels=c("NEVER",
  #     "ONCE",
  #     "TWICE",
  #     "3-5 TIMES",
  #     "6-10 TIMES",
  #     "11-50 TIMES",
  #     "MORE THAN 50 TIMES"))
  # data$R0305400 <- factor(data$R0305400,
  #   levels=c(0.0,1.0,2.0,3.0,4.0,5.0,6.0),
  #   labels=c("NEVER",
  #     "ONCE",
  #     "TWICE",
  #     "3-5 TIMES",
  #     "6-10 TIMES",
  #     "11-50 TIMES",
  #     "MORE THAN 50 TIMES"))
  # data$R0305500 <- factor(data$R0305500,
  #   levels=c(0.0,1.0,2.0,3.0,4.0,5.0,6.0),
  #   labels=c("NEVER",
  #     "ONCE",
  #     "TWICE",
  #     "3-5 TIMES",
  #     "6-10 TIMES",
  #     "11-50 TIMES",
  #     "MORE THAN 50 TIMES"))
  # data$R0305600 <- factor(data$R0305600,
  #   levels=c(0.0,1.0,2.0,3.0,4.0,5.0,6.0),
  #   labels=c("NEVER",
  #     "ONCE",
  #     "TWICE",
  #     "3-5 TIMES",
  #     "6-10 TIMES",
  #     "11-50 TIMES",
  #     "MORE THAN 50 TIMES"))
  # data$R0305900 <- factor(data$R0305900,
  #   levels=c(0.0,1.0,2.0,3.0,4.0,5.0,6.0),
  #   labels=c("NEVER",
  #     "ONCE",
  #     "TWICE",
  #     "3-5 TIMES",
  #     "6-10 TIMES",
  #     "11-50 TIMES",
  #     "MORE THAN 50 TIMES"))
  # data$R0306000 <- factor(data$R0306000,
  #   levels=c(0.0,1.0,2.0,3.0,4.0,5.0,6.0),
  #   labels=c("NEVER",
  #     "ONCE",
  #     "TWICE",
  #     "3-5 TIMES",
  #     "6-10 TIMES",
  #     "11-50 TIMES",
  #     "MORE THAN 50 TIMES"))
  # data$R0306100 <- factor(data$R0306100,
  #   levels=c(0.0,1.0,2.0,3.0,4.0,5.0,6.0),
  #   labels=c("NEVER",
  #     "ONCE",
  #     "TWICE",
  #     "3-5 TIMES",
  #     "6-10 TIMES",
  #     "11-50 TIMES",
  #     "MORE THAN 50 TIMES"))
  # data$R0306200 <- factor(data$R0306200,
  #   levels=c(0.0,1.0,2.0,3.0,4.0,5.0,6.0),
  #   labels=c("NEVER",
  #     "ONCE",
  #     "TWICE",
  #     "3-5 TIMES",
  #     "6-10 TIMES",
  #     "11-50 TIMES",
  #     "MORE THAN 50 TIMES"))
  # data$R0306300 <- factor(data$R0306300,
  #   levels=c(0.0,1.0,2.0,3.0,4.0,5.0,6.0),
  #   labels=c("NEVER",
  #     "ONCE",
  #     "TWICE",
  #     "3-5 TIMES",
  #     "6-10 TIMES",
  #     "11-50 TIMES",
  #     "MORE THAN 50 TIMES"))
  # data$R0306400 <- factor(data$R0306400,
  #   levels=c(0.0,1.0,2.0,3.0,4.0,5.0,6.0),
  #   labels=c("NEVER",
  #     "ONCE",
  #     "TWICE",
  #     "3-5 TIMES",
  #     "6-10 TIMES",
  #     "11-50 TIMES",
  #     "MORE THAN 50 TIMES"))
  # data$R0306500 <- factor(data$R0306500,
  #   levels=c(0.0,1.0,2.0,3.0,4.0,5.0,6.0),
  #   labels=c("NEVER",
  #     "ONCE",
  #     "TWICE",
  #     "3-5 TIMES",
  #     "6-10 TIMES",
  #     "11-50 TIMES",
  #     "MORE THAN 50 TIMES"))
  data$R0306700 <- factor(data$R0306700,
                          levels=c(0.0,1.0),
                          labels=c("NO",
                                   "YES"))

  data$R0307100 <- factor(data$R0307100,
                          levels=c(0.0,1.0),
                          labels=c("NO",
                                   "YES"))

  data$R0307700 <- factor(data$R0307700,
                          levels=c(0.0,1.0),
                          labels=c("NO",
                                   "YES"))
  data$R0307800 <- factor(data$R0307800,
                          levels=c(0.0,1.0),
                          labels=c("NO",
                                   "YES"))

  data$R0308300 <- factor(data$R0308300,
                          levels=c(1.0),
                          labels=c("ASSAULT"))
  data$R0308400 <- factor(data$R0308400,
                          levels=c(2.0),
                          labels=c("ROBBERY"))
  data$R0308500 <- factor(data$R0308500,
                          levels=c(3.0),
                          labels=c("THEFT"))
  data$R0308600 <- factor(data$R0308600,
                          levels=c(4.0),
                          labels=c("THEFT BY DECEPTION"))
  data$R0308700 <- factor(data$R0308700,
                          levels=c(5.0),
                          labels=c("CONVICTED REGARDING STOLEN PROPERTY"))
  data$R0308800 <- factor(data$R0308800,
                          levels=c(6.0),
                          labels=c("DESTRUCTION OF PROPERTY"))
  data$R0308900 <- factor(data$R0308900,
                          levels=c(7.0),
                          labels=c("OTHER PROPERTY OFFENSE"))
  data$R0309000 <- factor(data$R0309000,
                          levels=c(8.0),
                          labels=c("GAMBLING OFFENSE"))
  data$R0309100 <- factor(data$R0309100,
                          levels=c(9.0),
                          labels=c("COMMERCIAL VICE"))
  data$R0309200 <- factor(data$R0309200,
                          levels=c(10.0),
                          labels=c("POSSESSION OF MARIJUANA/HASHISH"))
  data$R0309300 <- factor(data$R0309300,
                          levels=c(11.0),
                          labels=c("SELLING MARIJUANA/HASHISH"))
  data$R0309400 <- factor(data$R0309400,
                          levels=c(12.0),
                          labels=c("POSSESSION OF OTHER ILLICIT DRUGS"))
  data$R0309500 <- factor(data$R0309500,
                          levels=c(13.0),
                          labels=c("SALE/MANUFACTURE OF OTHER ILLICIT DRUGS"))
  data$R0309600 <- factor(data$R0309600,
                          levels=c(14.0),
                          labels=c("MAJOR TRAFFIC OFFENSE"))
  data$R0309800 <- factor(data$R0309800,
                          levels=c(16.0),
                          labels=c("STATUS OFFENSE"))
  data$R0309900 <- factor(data$R0309900,
                          levels=c(17.0),
                          labels=c("OTHER OFFENSE"))
  data$R0310000 <- factor(data$R0310000,
                          levels=c(0.0,1.0),
                          labels=c("NO",
                                   "YES"))
  data$R0310100 <- factor(data$R0310100,
                          levels=c(0.0,1.0),
                          labels=c("NO",
                                   "YES"))

  data$R0310600 <- factor(data$R0310600,
                          levels=c(0.0,1.0),
                          labels=c("NO",
                                   "YES"))

  data$R0310900 <- factor(data$R0310900,
                          levels=c(0.0,1.0),
                          labels=c("NO",
                                   "YES"))

  data$R0406310 <- factor(data$R0406310,
                          levels=c(60.0,61.0,62.0,63.0,64.0,65.0,66.0),
                          labels=c("PARENT REFUSAL/BREAKOFF",
                                   "YOUTH REFUSAL/BREAKOFF",
                                   "PARENT AND YOUTH REFUSAL/BREAKOFF",
                                   "UNABLE TO LOCATE FAMILY UNIT AND YOUTH",
                                   "UNABLE TO LOCATE YOUTH",
                                   "DECEASED",
                                   "OTHER"))
  data$R0618810 <- factor(data$R0618810,
                          levels=c(60.0,61.0,62.0,63.0,64.0,65.0,66.0),
                          labels=c("PARENT REFUSAL/BREAKOFF",
                                   "YOUTH REFUSAL/BREAKOFF",
                                   "PARENT AND YOUTH REFUSAL/BREAKOFF",
                                   "UNABLE TO LOCATE FAMILY UNIT AND YOUTH",
                                   "UNABLE TO LOCATE YOUTH",
                                   "DECEASED",
                                   "OTHER"))
  data$R0898510 <- factor(data$R0898510,
                          levels=c(60.0,61.0,62.0,63.0,64.0,65.0,66.0,67.0),
                          labels=c("PARENT REFUSAL/BREAKOFF",
                                   "YOUTH REFUSAL/BREAKOFF",
                                   "PARENT & YOUTH REFUSAL/BREAKOFF",
                                   "UNABLE TO LOCATE FAMILY UNIT & YOUTH",
                                   "UNABLE TO LOCATE YOUTH",
                                   "DECEASED",
                                   "OTHER",
                                   "DO NOT REFIELD (VERY DIFFICULT CASES)"))
  data$R1144710 <- factor(data$R1144710,
                          levels=c(60.0,61.0,62.0,63.0,64.0,65.0,66.0,67.0),
                          labels=c("PARENT REFUSAL/BREAKOFF",
                                   "YOUTH REFUSAL/BREAKOFF",
                                   "PARENT & YOUTH REFUSAL/BREAKOFF",
                                   "UNABLE TO LOCATE FAMILY UNIT & YOUTH",
                                   "UNABLE TO LOCATE YOUTH",
                                   "DECEASED",
                                   "OTHER",
                                   "DO NOT REFIELD (VERY DIFFICULT CASES)"))
  data$R1519910 <- factor(data$R1519910,
                          levels=c(60.0,61.0,62.0,63.0,64.0,65.0,66.0,67.0),
                          labels=c("PARENT REFUSAL/BREAKOFF",
                                   "YOUTH REFUSAL/BREAKOFF",
                                   "PARENT & YOUTH REFUSAL/BREAKOFF",
                                   "UNABLE TO LOCATE FAMILY UNIT & YOUTH",
                                   "UNABLE TO LOCATE YOUTH",
                                   "DECEASED",
                                   "OTHER",
                                   "DO NOT REFIELD (VERY DIFFICULT CASES)"))
  data$R1890300 <- factor(data$R1890300,
                          levels=c(60.0,61.0,62.0,63.0,64.0,65.0,66.0,67.0,68.0),
                          labels=c("PARENT REFUSAL/BREAKOFF",
                                   "YOUTH REFUSAL/BREAKOFF",
                                   "PARENT & YOUTH REFUSAL/BREAKOFF",
                                   "UNABLE TO LOCATE FAMILY UNIT & YOUTH",
                                   "UNABLE TO LOCATE YOUTH",
                                   "DECEASED",
                                   "OTHER",
                                   "DO NOT REFIELD (VERY DIFFICULT CASES)",
                                   "MILITARY SAMPLE DROPPED"))
  data$R2257400 <- factor(data$R2257400,
                          levels=c(60.0,61.0,62.0,63.0,64.0,65.0,66.0,67.0,68.0),
                          labels=c("PARENT REFUSAL/BREAKOFF",
                                   "YOUTH REFUSAL/BREAKOFF",
                                   "PARENT & YOUTH REFUSAL/BREAKOFF",
                                   "UNABLE TO LOCATE FAMILY UNIT & YOUTH",
                                   "UNABLE TO LOCATE YOUTH",
                                   "DECEASED",
                                   "OTHER",
                                   "DO NOT REFIELD (VERY DIFFICULT CASES)",
                                   "MILITARY SAMPLE DROPPED"))
  data$R2444600 <- factor(data$R2444600,
                          levels=c(60.0,61.0,62.0,63.0,64.0,65.0,66.0,67.0,68.0),
                          labels=c("PARENT REFUSAL/BREAKOFF",
                                   "YOUTH REFUSAL/BREAKOFF",
                                   "PARENT & YOUTH REFUSAL/BREAKOFF",
                                   "UNABLE TO LOCATE FAMILY UNIT & YOUTH",
                                   "UNABLE TO LOCATE YOUTH",
                                   "DECEASED",
                                   "OTHER",
                                   "DO NOT REFIELD (VERY DIFFICULT CASES)",
                                   "MILITARY SAMPLE DROPPED"))
  data$R2870100 <- factor(data$R2870100,
                          levels=c(60.0,61.0,62.0,63.0,64.0,65.0,66.0,67.0,68.0),
                          labels=c("PARENT REFUSAL/BREAKOFF",
                                   "YOUTH REFUSAL/BREAKOFF",
                                   "PARENT & YOUTH REFUSAL/BREAKOFF",
                                   "UNABLE TO LOCATE FAMILY UNIT & YOUTH",
                                   "UNABLE TO LOCATE YOUTH",
                                   "DECEASED",
                                   "OTHER",
                                   "DO NOT REFIELD (VERY DIFFICULT CASES)",
                                   "MILITARY SAMPLE DROPPED"))
  data$R3073900 <- factor(data$R3073900,
                          levels=c(60.0,61.0,62.0,63.0,64.0,65.0,66.0,67.0,68.0),
                          labels=c("PARENT REFUSAL/BREAKOFF",
                                   "YOUTH REFUSAL/BREAKOFF",
                                   "PARENT & YOUTH REFUSAL/BREAKOFF",
                                   "UNABLE TO LOCATE FAMILY UNIT & YOUTH",
                                   "UNABLE TO LOCATE YOUTH",
                                   "DECEASED",
                                   "OTHER",
                                   "DO NOT REFIELD (VERY DIFFICULT CASES)",
                                   "MILITARY SAMPLE DROPPED"))
  data$R3400500 <- factor(data$R3400500,
                          levels=c(60.0,61.0,62.0,63.0,64.0,65.0,66.0,67.0,68.0),
                          labels=c("PARENT REFUSAL/BREAKOFF",
                                   "YOUTH REFUSAL/BREAKOFF",
                                   "PARENT & YOUTH REFUSAL/BREAKOFF",
                                   "UNABLE TO LOCATE FAMILY UNIT & YOUTH",
                                   "UNABLE TO LOCATE YOUTH",
                                   "DECEASED",
                                   "OTHER",
                                   "DO NOT REFIELD (VERY DIFFICULT CASES)",
                                   "MILITARY SAMPLE DROPPED"))
  data$R3655900 <- factor(data$R3655900,
                          levels=c(60.0,61.0,62.0,63.0,64.0,65.0,66.0,67.0,68.0,69.0,70.0),
                          labels=c("PARENT REFUSAL/BREAKOFF",
                                   "YOUTH REFUSAL/BREAKOFF",
                                   "PARENT & YOUTH REFUSAL/BREAKOFF",
                                   "UNABLE TO LOCATE FAMILY UNIT & YOUTH",
                                   "UNABLE TO LOCATE YOUTH",
                                   "DECEASED",
                                   "OTHER",
                                   "DO NOT REFIELD (VERY DIFFICULT CASES)",
                                   "MILITARY SAMPLE DROPPED",
                                   "SUPPLEMENTAL MALE POOR WHITE SAMPLE DROPPED",
                                   "SUPPLEMENTAL FEMALE POOR WHITE SAMPLE DROPPED"))
  data$R4006400 <- factor(data$R4006400,
                          levels=c(60.0,61.0,62.0,63.0,64.0,65.0,66.0,67.0,68.0,69.0,70.0),
                          labels=c("PARENT REFUSAL/BREAKOFF",
                                   "YOUTH REFUSAL/BREAKOFF",
                                   "PARENT & YOUTH REFUSAL/BREAKOFF",
                                   "UNABLE TO LOCATE FAMILY UNIT & YOUTH",
                                   "UNABLE TO LOCATE YOUTH",
                                   "DECEASED",
                                   "OTHER",
                                   "DO NOT REFIELD (VERY DIFFICULT CASES)",
                                   "MILITARY SAMPLE DROPPED",
                                   "SUPPLEMENTAL MALE POOR WHITE SAMPLE DROPPED",
                                   "SUPPLEMENTAL FEMALE POOR WHITE SAMPLE DROPPED"))
  data$R4417500 <- factor(data$R4417500,
                          levels=c(60.0,61.0,62.0,63.0,64.0,65.0,66.0,67.0,68.0,69.0,70.0),
                          labels=c("PARENT REFUSAL/BREAKOFF",
                                   "YOUTH REFUSAL/BREAKOFF",
                                   "PARENT & YOUTH REFUSAL/BREAKOFF",
                                   "UNABLE TO LOCATE FAMILY UNIT & YOUTH",
                                   "UNABLE TO LOCATE YOUTH",
                                   "DECEASED",
                                   "OTHER",
                                   "DO NOT REFIELD (VERY DIFFICULT CASES)",
                                   "MILITARY SAMPLE DROPPED",
                                   "SUPPLEMENTAL MALE POOR WHITE SAMPLE DROPPED",
                                   "SUPPLEMENTAL FEMALE POOR WHITE SAMPLE DROPPED"))
  data$R4980800 <- factor(data$R4980800,
                          levels=c(1.0,2.0,3.0,4.0,5.0),
                          labels=c("Happened 3 or more times in the past year",
                                   "Happened 2 times in the past year",
                                   "Happened 1 time in the past year",
                                   "Happened in lifetime other than in past year",
                                   "Never happened"))
  data$R5080500 <- factor(data$R5080500,
                          levels=c(60.0,61.0,62.0,63.0,64.0,65.0,66.0,67.0,68.0,69.0,70.0),
                          labels=c("60: 60  PARENT REFUSAL/BREAKOFF",
                                   "61: 61  YOUTH REFUSAL/BREAKOFF",
                                   "62: 62  PARENT & YOUTH REFUSAL/BREAKOFF",
                                   "63: 63  UNABLE TO LOCATE FAMILY UNIT & YOUTH",
                                   "64: 64  UNABLE TO LOCATE YOUTH",
                                   "65: 65  DECEASED",
                                   "66: 66  OTHER",
                                   "67: 67  DO NOT REFIELD (VERY DIFFICULT CASE)",
                                   "68: 68  MILITARY SAMPLE DROPPED",
                                   "69: 69  SUPPLEMENTAL MALE POOR WHITE SAMPLE DROPPED",
                                   "70: 70  SUPPLEMENTAL FEMALE POOR WHITE SAMPLE DROPPED"))
  data$R5165800 <- factor(data$R5165800,
                          levels=c(60.0,61.0,62.0,63.0,64.0,65.0,66.0,67.0,68.0,69.0,70.0),
                          labels=c("60: PARENT REFUSAL/BREAKOFF",
                                   "61: YOUTH REFUSAL/BREAKOFF",
                                   "62: PARENT & YOUTH REFUSAL/BREAKOFF",
                                   "63: UNABLE TO LOCATE FAMILY UNIT & YOUTH",
                                   "64: UNABLE TO LOCATE YOUTH",
                                   "65: DECEASED",
                                   "66: OTHER",
                                   "67: DO NOT REFIELD (VERY DIFFICULT CASE)",
                                   "68: MILITARY SAMPLE DROPPED",
                                   "69: SUPPLEMENTAL MALE POOR WHITE SAMPLE DROPPED",
                                   "70: SUPPLEMENTAL FEMALE POOR WHITE SAMPLE DROPPED"))
  data$R6478500 <- factor(data$R6478500,
                          levels=c(60.0,61.0,62.0,63.0,64.0,65.0,66.0,67.0,68.0,69.0,70.0),
                          labels=c("60: 60  PARENT REFUSAL/BREAKOFF",
                                   "61: 61  YOUTH REFUSAL/BREAKOFF",
                                   "62: 62  PARENT & YOUTH REFUSAL/BREAKOFF",
                                   "63: 63  UNABLE TO LOCATE FAMILY UNIT & YOUTH",
                                   "64: 64  UNABLE TO LOCATE YOUTH",
                                   "65: 65  DECEASED",
                                   "66: 66  OTHER",
                                   "67: 67  DO NOT REFIELD (VERY DIFFICULT CASE)",
                                   "68: 68  MILITARY SAMPLE DROPPED",
                                   "69: 69  SUPPLEMENTAL MALE POOR WHITE SAMPLE DROPPED",
                                   "70: 70  SUPPLEMENTAL FEMALE POOR WHITE SAMPLE DROPPED"))
  data$R7006300 <- factor(data$R7006300,
                          levels=c(60.0,61.0,62.0,63.0,64.0,65.0,66.0,67.0,68.0,69.0,70.0,71.0),
                          labels=c("60: PARENT REFUSAL/BREAKOFF",
                                   "61: YOUTH REFUSAL/BREAKOFF",
                                   "62: PARENT & YOUTH REFUSAL/BREAKOFF",
                                   "63: UNABLE TO LOCATE FAMILY UNIT & YOUTH",
                                   "64: UNABLE TO LOCATE YOUTH",
                                   "65: DECEASED",
                                   "66: OTHER",
                                   "67: DO NOT REFIELD (VERY DIFFICULT CASE)",
                                   "68: MILITARY SAMPLE DROPPED",
                                   "69: SUPPLEMENTAL MALE POOR WHITE SAMPLE DROPPED",
                                   "70: SUPPLEMENTAL FEMALE POOR WHITE SAMPLE DROPPED",
                                   "71: YOUTH REFUSAL - VERY DIFFICULT CASE"))
  data$R7703500 <- factor(data$R7703500,
                          levels=c(60.0,61.0,62.0,63.0,64.0,65.0,66.0,67.0,68.0,69.0,70.0,71.0,72.0),
                          labels=c("60: 60  PARENT REFUSAL/BREAKOFF",
                                   "61: 61  YOUTH REFUSAL/BREAKOFF",
                                   "62: 62  PARENT & YOUTH REFUSAL/BREAKOFF",
                                   "63: 63  UNABLE TO LOCATE FAMILY UNIT & YOUTH",
                                   "64: 64  UNABLE TO LOCATE YOUTH",
                                   "65: 65  DECEASED",
                                   "66: 66  OTHER",
                                   "67: 67  DO NOT REFIELD (VERY DIFFICULT CASE)",
                                   "68: 68  MILITARY SAMPLE DROPPED",
                                   "69: 69  SUPPLEMENTAL MALE POOR WHITE SAMPLE DROPPED",
                                   "70: 70  SUPPLEMENTAL FEMALE POOR WHITE SAMPLE DROPPED",
                                   "71: 71  YOUTH REFUSAL - VERY DIFFICULT CASE",
                                   "72: 72  NOT FIELDED IN CURRENT SURVEY YEAR - VERY DIFFICULT CASE"))
  data$R8495900 <- factor(data$R8495900,
                          levels=c(60.0,61.0,62.0,63.0,64.0,65.0,66.0,67.0,68.0,69.0,70.0,71.0,72.0,73.0,74.0),
                          labels=c("60: 60  PARENT REFUSAL/BREAKOFF",
                                   "61: 61  YOUTH REFUSAL/BREAKOFF",
                                   "62: 62  PARENT & YOUTH REFUSAL/BREAKOFF",
                                   "63: 63  UNABLE TO LOCATE FAMILY UNIT & YOUTH",
                                   "64: 64  UNABLE TO LOCATE YOUTH",
                                   "65: 65  DECEASED",
                                   "66: 66  OTHER",
                                   "67: 67  DO NOT REFIELD (VERY DIFFICULT CASE)",
                                   "68: 68  MILITARY SAMPLE DROPPED",
                                   "69: 69  SUPPLEMENTAL MALE POOR WHITE SAMPLE DROPPED",
                                   "70: 70  SUPPLEMENTAL FEMALE POOR WHITE SAMPLE DROPPED",
                                   "71: 71  YOUTH REFUSAL - VERY DIFFICULT CASE",
                                   "72: 72  NOT FIELDED IN CURRENT SURVEY YEAR - VERY DIFFICULT CASE",
                                   "73: 73  NOT INTERVIEWED - INCARCERATED",
                                   "74: 74  NOT INTERVIEWED - IN MILITARY"))
  data$T0987500 <- factor(data$T0987500,
                          levels=c(60.0,61.0,62.0,63.0,64.0,65.0,66.0,67.0,68.0,69.0,70.0,71.0,72.0,73.0,74.0),
                          labels=c("60: 60  PARENT REFUSAL/BREAKOFF",
                                   "61: 61  YOUTH REFUSAL/BREAKOFF",
                                   "62: 62  PARENT & YOUTH REFUSAL/BREAKOFF",
                                   "63: 63  UNABLE TO LOCATE FAMILY UNIT & YOUTH",
                                   "64: 64  UNABLE TO LOCATE YOUTH",
                                   "65: 65  DECEASED",
                                   "66: 66  OTHER",
                                   "67: 67  DO NOT REFIELD (VERY DIFFICULT CASE)",
                                   "68: 68  MILITARY SAMPLE DROPPED",
                                   "69: 69  SUPPLEMENTAL MALE POOR WHITE SAMPLE DROPPED",
                                   "70: 70  SUPPLEMENTAL FEMALE POOR WHITE SAMPLE DROPPED",
                                   "71: 71  YOUTH REFUSAL - VERY DIFFICULT CASE",
                                   "72: 72  NOT FIELDED IN CURRENT SURVEY YEAR - VERY DIFFICULT CASE",
                                   "73: 73  NOT INTERVIEWED - INCARCERATED",
                                   "74: 74  NOT INTERVIEWED - IN MILITARY"))
  data$T2209800 <- factor(data$T2209800,
                          levels=c(60.0,61.0,62.0,63.0,64.0,65.0,66.0,67.0,68.0,69.0,70.0,71.0,72.0,73.0,74.0),
                          labels=c("60: 60  PARENT REFUSAL/BREAKOFF",
                                   "61: 61  YOUTH REFUSAL/BREAKOFF",
                                   "62: 62  PARENT & YOUTH REFUSAL/BREAKOFF",
                                   "63: 63  UNABLE TO LOCATE FAMILY UNIT & YOUTH",
                                   "64: 64  UNABLE TO LOCATE YOUTH",
                                   "65: 65  DECEASED",
                                   "66: 66  OTHER",
                                   "67: 67  DO NOT REFIELD (VERY DIFFICULT CASE)",
                                   "68: 68  MILITARY SAMPLE DROPPED",
                                   "69: 69  SUPPLEMENTAL MALE POOR WHITE SAMPLE DROPPED",
                                   "70: 70  SUPPLEMENTAL FEMALE POOR WHITE SAMPLE DROPPED",
                                   "71: 71  YOUTH REFUSAL - VERY DIFFICULT CASE",
                                   "72: 72  NOT FIELDED IN CURRENT SURVEY YEAR - VERY DIFFICULT CASE",
                                   "73: 73  NOT INTERVIEWED - INCARCERATED",
                                   "74: 74  NOT INTERVIEWED - IN MILITARY"))
  data$T3107600 <- factor(data$T3107600,
                          levels=c(60.0,61.0,62.0,63.0,64.0,65.0,66.0,67.0,68.0,69.0,70.0,71.0,72.0,73.0,74.0),
                          labels=c("60: 60  PARENT REFUSAL/BREAKOFF",
                                   "61: 61  YOUTH REFUSAL/BREAKOFF",
                                   "62: 62  PARENT & YOUTH REFUSAL/BREAKOFF",
                                   "63: 63  UNABLE TO LOCATE FAMILY UNIT & YOUTH",
                                   "64: 64  UNABLE TO LOCATE YOUTH",
                                   "65: 65  DECEASED",
                                   "66: 66  OTHER",
                                   "67: 67  DO NOT REFIELD (VERY DIFFICULT CASE)",
                                   "68: 68  MILITARY SAMPLE DROPPED",
                                   "69: 69  SUPPLEMENTAL MALE POOR WHITE SAMPLE DROPPED",
                                   "70: 70  SUPPLEMENTAL FEMALE POOR WHITE SAMPLE DROPPED",
                                   "71: 71  YOUTH REFUSAL - VERY DIFFICULT CASE",
                                   "72: 72  NOT FIELDED IN CURRENT SURVEY YEAR - VERY DIFFICULT CASE",
                                   "73: 73  NOT INTERVIEWED - INCARCERATED",
                                   "74: 74  NOT INTERVIEWED - IN MILITARY"))
  data$T4112100 <- factor(data$T4112100,
                          levels=c(60.0,61.0,62.0,63.0,64.0,65.0,66.0,67.0,68.0,69.0,70.0,71.0,72.0,73.0,74.0),
                          labels=c("60: 60  PARENT REFUSAL/BREAKOFF",
                                   "61: 61  YOUTH REFUSAL/BREAKOFF",
                                   "62: 62  PARENT & YOUTH REFUSAL/BREAKOFF",
                                   "63: 63  UNABLE TO LOCATE FAMILY UNIT & YOUTH",
                                   "64: 64  UNABLE TO LOCATE YOUTH",
                                   "65: 65  DECEASED",
                                   "66: 66  OTHER",
                                   "67: 67  DO NOT REFIELD (VERY DIFFICULT CASE)",
                                   "68: 68  MILITARY SAMPLE DROPPED",
                                   "69: 69  SUPPLEMENTAL MALE POOR WHITE SAMPLE DROPPED",
                                   "70: 70  SUPPLEMENTAL FEMALE POOR WHITE SAMPLE DROPPED",
                                   "71: 71  YOUTH REFUSAL - VERY DIFFICULT CASE",
                                   "72: 72  NOT FIELDED IN CURRENT SURVEY YEAR - VERY DIFFICULT CASE",
                                   "73: 73  NOT INTERVIEWED - INCARCERATED",
                                   "74: 74  NOT INTERVIEWED - IN MILITARY"))
  data$T5022300 <- factor(data$T5022300,
                          levels=c(60.0,61.0,62.0,63.0,64.0,65.0,66.0,67.0,68.0,69.0,70.0,71.0,72.0,73.0,74.0),
                          labels=c("60: 60  PARENT REFUSAL/BREAKOFF",
                                   "61: 61  YOUTH REFUSAL/BREAKOFF",
                                   "62: 62  PARENT & YOUTH REFUSAL/BREAKOFF",
                                   "63: 63  UNABLE TO LOCATE FAMILY UNIT & YOUTH",
                                   "64: 64  UNABLE TO LOCATE YOUTH",
                                   "65: 65  DECEASED",
                                   "66: 66  OTHER",
                                   "67: 67  DO NOT REFIELD (VERY DIFFICULT CASE)",
                                   "68: 68  MILITARY SAMPLE DROPPED",
                                   "69: 69  SUPPLEMENTAL MALE POOR WHITE SAMPLE DROPPED",
                                   "70: 70  SUPPLEMENTAL FEMALE POOR WHITE SAMPLE DROPPED",
                                   "71: 71  YOUTH REFUSAL - VERY DIFFICULT CASE",
                                   "72: 72  NOT FIELDED IN CURRENT SURVEY YEAR - VERY DIFFICULT CASE",
                                   "73: 73  NOT INTERVIEWED - INCARCERATED",
                                   "74: 74  NOT INTERVIEWED - IN MILITARY"))
  data$T5770600 <- factor(data$T5770600,
                          levels=c(60.0,61.0,62.0,63.0,64.0,65.0,66.0,67.0,68.0,69.0,70.0,71.0,72.0,73.0,74.0,75.0),
                          labels=c("60: 60  PARENT REFUSAL/BREAKOFF",
                                   "61: 61  YOUTH REFUSAL/BREAKOFF",
                                   "62: 62  PARENT & YOUTH REFUSAL/BREAKOFF",
                                   "63: 63  UNABLE TO LOCATE FAMILY UNIT & YOUTH",
                                   "64: 64  UNABLE TO LOCATE YOUTH",
                                   "65: 65  DECEASED",
                                   "66: 66  OTHER",
                                   "67: 67  DO NOT REFIELD (VERY DIFFICULT CASE)",
                                   "68: 68  MILITARY SAMPLE DROPPED",
                                   "69: 69  SUPPLEMENTAL MALE POOR WHITE SAMPLE DROPPED",
                                   "70: 70  SUPPLEMENTAL FEMALE POOR WHITE SAMPLE DROPPED",
                                   "71: 71  YOUTH REFUSAL - VERY DIFFICULT CASE",
                                   "72: 72  NOT FIELDED IN CURRENT SURVEY YEAR - VERY DIFFICULT CASE",
                                   "73: 73  NOT INTERVIEWED - INCARCERATED",
                                   "74: 74  NOT INTERVIEWED - IN MILITARY",
                                   "75: 75 DECEASED - MEMBER OF DROPPED SPECIAL SAMPLE"))
  return(data)
}
