#gen 1 depression

new_data <- readr::read_csv('data/df_dep_gen1/df_dep_gen1.csv',
                            col_types = cols())
names(new_data) <- c('H0000300',
                     'H0000400',
                     'H0000500',
                     'H0000600',
                     'H0000700',
                     'H0000800',
                     'H0000900',
                     'H0001000',
                     'H0001100',
                     'H0001101',
                     'H0003900',
                     'H0004000',
                     'H0004500',
                     'H0006900',
                     'H0007000',
                     'H0007001',
                     'H0007100',
                     'H0008600',
                     'H0013301',
                     'H0013400',
                     'H0013401',
                     'H0013402',
                     'H0013403',
                     'H0013404',
                     'H0013405',
                     'H0013406',
                     'H0013407',
                     'H0013408',
                     'H0016400',
                     'H0016500',
                     'H0016700',
                     'H0016800',
                     'H0016900',
                     'H0017000',
                     'H0020800',
                     'H0020900',
                     'H0020901',
                     'H0021000',
                     'H0021100',
                     'H0021200',
                     'H0021300',
                     'H0021301',
                     'H0021400',
                     'R0000100',
                     'R0144600',
                     'R0173600',
                     'R3894900',
                     'R3895000',
                     'R3895100',
                     'R3895200',
                     'R3895300',
                     'R3895400',
                     'R3895500',
                     'R3895600',
                     'R3895700',
                     'R3895800',
                     'R3895900',
                     'R3896000',
                     'R3896100',
                     'R3896200',
                     'R3896300',
                     'R3896400',
                     'R3896500',
                     'R3896600',
                     'R3896700',
                     'R3896800',
                     'R3896810',
                     'R3896811',
                     'R3896820',
                     'R4978300',
                     'R4978400',
                     'R4978500',
                     'R4978600',
                     'R4978700',
                     'R4978800',
                     'R4978900',
                     'R4978910',
                     'T5006600',
                     'T5740700')


# Handle missing values

new_data[new_data == -1] = NA  # Refused
new_data[new_data == -2] = NA  # Dont know
new_data[new_data == -3] = NA  # Invalid missing
new_data[new_data == -4] = NA  # Valid missing
new_data[new_data == -5] = NA  # Non-interview


# If there are values not categorized they will be represented as NA

vallabels = function(data) {
  data$H0000300 <- factor(data$H0000300,
                          levels=c(0.0,1.0,2.0,3.0),
                          labels=c("Rarely/None of the time/1 Day",
                                   "Some/A little of the time/1-2 Days",
                                   "Occasionally/Moderate amount of the time/3-4 Days",
                                   "Most/All of the time/5-7 Days"))
  data$H0000400 <- factor(data$H0000400,
                          levels=c(0.0,1.0,2.0,3.0),
                          labels=c("Rarely/None of the time/1 Day",
                                   "Some/A little of the time/1-2 Days",
                                   "Occasionally/Moderate amount of the time/3-4 Days",
                                   "Most/All of the time/5-7 Days"))
  data$H0000500 <- factor(data$H0000500,
                          levels=c(0.0,1.0,2.0,3.0),
                          labels=c("Rarely/None of the time/1 Day",
                                   "Some/A little of the time/1-2 Days",
                                   "Occasionally/Moderate amount of the time/3-4 Days",
                                   "Most/All of the time/5-7 Days"))
  data$H0000600 <- factor(data$H0000600,
                          levels=c(0.0,1.0,2.0,3.0),
                          labels=c("Rarely/None of the time/1 Day",
                                   "Some/A little of the time/1-2 Days",
                                   "Occasionally/Moderate amount of the time/3-4 Days",
                                   "Most/All of the time/5-7 Days"))
  data$H0000700 <- factor(data$H0000700,
                          levels=c(0.0,1.0,2.0,3.0),
                          labels=c("Rarely/None of the time/1 Day",
                                   "Some/A little of the time/1-2 Days",
                                   "Occasionally/Moderate amount of the time/3-4 Days",
                                   "Most/All of the time/5-7 Days"))
  data$H0000800 <- factor(data$H0000800,
                          levels=c(0.0,1.0,2.0,3.0),
                          labels=c("Rarely/None of the time/1 Day",
                                   "Some/A little of the time/1-2 Days",
                                   "Occasionally/Moderate amount of the time/3-4 Days",
                                   "Most/All of the time/5-7 Days"))
  data$H0000900 <- factor(data$H0000900,
                          levels=c(0.0,1.0,2.0,3.0),
                          labels=c("Rarely/None of the time/1 Day",
                                   "Some/A little of the time/1-2 Days",
                                   "Occasionally/Moderate amount of the time/3-4 Days",
                                   "Most/All of the time/5-7 Days"))
  data$H0001000 <- factor(data$H0001000,
                          levels=c(0.0,1.0,2.0,3.0),
                          labels=c("Rarely/None of the time/1 Day",
                                   "Some/A little of the time/1-2 Days",
                                   "Occasionally/Moderate amount of the time/3-4 Days",
                                   "Most/All of the time/5-7 Days"))
  data$H0001100 <- factor(data$H0001100,
                          levels=c(0.0,1.0,2.0,3.0),
                          labels=c("Rarely/None of the time/1 Day",
                                   "Some/A little of the time/1-2 Days",
                                   "Occasionally/Moderate amount of the time/3-4 Days",
                                   "Most/All of the time/5-7 Days"))
  data$H0003900 <- factor(data$H0003900,
                          levels=c(0.0,1.0),
                          labels=c("NO",
                                   "YES"))
  data$H0004000 <- factor(data$H0004000,
                          levels=c(0.0,1.0),
                          labels=c("NO",
                                   "YES"))
  data$H0004500 <- factor(data$H0004500,
                          levels=c(1.0,2.0,3.0,4.0,5.0,6.0),
                          labels=c("All the time",
                                   "Most of the time",
                                   "A good bit of the time",
                                   "Some of the time",
                                   "A little of the time",
                                   "None of the time"))
  data$H0006900 <- factor(data$H0006900,
                          levels=c(0.0,1.0),
                          labels=c("NO",
                                   "YES"))
  data$H0007000 <- factor(data$H0007000,
                          levels=c(1.0,2.0,3.0,4.0,5.0,6.0,7.0,8.0,9.0,10.0,11.0,12.0),
                          labels=c("1: January",
                                   "2: February",
                                   "3: March",
                                   "4: April",
                                   "5: May",
                                   "6: June",
                                   "7: July",
                                   "8: August",
                                   "9: September",
                                   "10: October",
                                   "11: November",
                                   "12: December"))

  data$H0007100 <- factor(data$H0007100,
                          levels=c(0.0,1.0),
                          labels=c("NO",
                                   "YES"))
  data$H0008600 <- factor(data$H0008600,
                          levels=c(0.0,1.0),
                          labels=c("NO",
                                   "YES"))

  data$H0013400 <- factor(data$H0013400,
                          levels=c(0.0,1.0,2.0,3.0),
                          labels=c("Rarely/None of the time/1 Day",
                                   "Some/A little of the time/1-2 Days",
                                   "Occasionally/Moderate amount of the time/3-4 Days",
                                   "Most/All of the time/5-7 Days"))
  data$H0013401 <- factor(data$H0013401,
                          levels=c(0.0,1.0,2.0,3.0),
                          labels=c("Rarely/None of the time/1 Day",
                                   "Some/A little of the time/1-2 Days",
                                   "Occasionally/Moderate amount of the time/3-4 Days",
                                   "Most/All of the time/5-7 Days"))
  data$H0013402 <- factor(data$H0013402,
                          levels=c(0.0,1.0,2.0,3.0),
                          labels=c("Rarely/None of the time/1 Day",
                                   "Some/A little of the time/1-2 Days",
                                   "Occasionally/Moderate amount of the time/3-4 Days",
                                   "Most/All of the time/5-7 Days"))
  data$H0013403 <- factor(data$H0013403,
                          levels=c(0.0,1.0,2.0,3.0),
                          labels=c("Rarely/None of the time/1 Day",
                                   "Some/A little of the time/1-2 Days",
                                   "Occasionally/Moderate amount of the time/3-4 Days",
                                   "Most/All of the time/5-7 Days"))
  data$H0013404 <- factor(data$H0013404,
                          levels=c(0.0,1.0,2.0,3.0),
                          labels=c("Rarely/None of the time/1 Day",
                                   "Some/A little of the time/1-2 Days",
                                   "Occasionally/Moderate amount of the time/3-4 Days",
                                   "Most/All of the time/5-7 Days"))
  data$H0013405 <- factor(data$H0013405,
                          levels=c(0.0,1.0,2.0,3.0),
                          labels=c("Rarely/None of the time/1 Day",
                                   "Some/A little of the time/1-2 Days",
                                   "Occasionally/Moderate amount of the time/3-4 Days",
                                   "Most/All of the time/5-7 Days"))
  data$H0013406 <- factor(data$H0013406,
                          levels=c(0.0,1.0,2.0,3.0),
                          labels=c("Rarely/None of the time/1 Day",
                                   "Some/A little of the time/1-2 Days",
                                   "Occasionally/Moderate amount of the time/3-4 Days",
                                   "Most/All of the time/5-7 Days"))
  data$H0013407 <- factor(data$H0013407,
                          levels=c(0.0,1.0,2.0,3.0),
                          labels=c("Rarely/None of the time/1 Day",
                                   "Some/A little of the time/1-2 Days",
                                   "Occasionally/Moderate amount of the time/3-4 Days",
                                   "Most/All of the time/5-7 Days"))
  data$H0013408 <- factor(data$H0013408,
                          levels=c(0.0,1.0,2.0,3.0),
                          labels=c("Rarely/None of the time/1 Day",
                                   "Some/A little of the time/1-2 Days",
                                   "Occasionally/Moderate amount of the time/3-4 Days",
                                   "Most/All of the time/5-7 Days"))
  data$H0016400 <- factor(data$H0016400,
                          levels=c(0.0,1.0),
                          labels=c("NO",
                                   "YES"))
  data$H0016500 <- factor(data$H0016500,
                          levels=c(0.0,1.0),
                          labels=c("NO",
                                   "YES"))
  data$H0016700 <- factor(data$H0016700,
                          levels=c(1.0,2.0,3.0,4.0,5.0,6.0),
                          labels=c("All the time",
                                   "Most of the time",
                                   "A good bit of the time",
                                   "Some of the time",
                                   "A little of the time",
                                   "None of the time"))
  data$H0016800 <- factor(data$H0016800,
                          levels=c(1.0,2.0,3.0,4.0,5.0,6.0),
                          labels=c("All the time",
                                   "Most of the time",
                                   "A good bit of the time",
                                   "Some of the time",
                                   "A little of the time",
                                   "None of the time"))
  data$H0016900 <- factor(data$H0016900,
                          levels=c(1.0,2.0,3.0,4.0,5.0,6.0),
                          labels=c("All the time",
                                   "Most of the time",
                                   "A good bit of the time",
                                   "Some of the time",
                                   "A little of the time",
                                   "None of the time"))
  data$H0017000 <- factor(data$H0017000,
                          levels=c(1.0,2.0,3.0,4.0,5.0,6.0),
                          labels=c("All the time",
                                   "Most of the time",
                                   "A good bit of the time",
                                   "Some of the time",
                                   "A little of the time",
                                   "None of the time"))
  data$H0020800 <- factor(data$H0020800,
                          levels=c(0.0,1.0),
                          labels=c("NO",
                                   "YES"))
  data$H0020900 <- factor(data$H0020900,
                          levels=c(1.0,2.0,3.0,4.0,5.0,6.0,7.0,8.0,9.0,10.0,11.0,12.0),
                          labels=c("1: January",
                                   "2: February",
                                   "3: March",
                                   "4: April",
                                   "5: May",
                                   "6: June",
                                   "7: July",
                                   "8: August",
                                   "9: September",
                                   "10: October",
                                   "11: November",
                                   "12: December"))

  data$H0021000 <- factor(data$H0021000,
                          levels=c(0.0,1.0),
                          labels=c("NO",
                                   "YES"))
  data$H0021100 <- factor(data$H0021100,
                          levels=c(0.0,1.0),
                          labels=c("0: 0  CONDITION DOES NOT APPLY",
                                   "1: 1  CONDITION APPLIES"))
  data$H0021200 <- factor(data$H0021200,
                          levels=c(0.0,1.0),
                          labels=c("NO",
                                   "YES"))
  data$H0021300 <- factor(data$H0021300,
                          levels=c(1.0,2.0,3.0,4.0,5.0,6.0,7.0,8.0,9.0,10.0,11.0,12.0),
                          labels=c("1: January",
                                   "2: February",
                                   "3: March",
                                   "4: April",
                                   "5: May",
                                   "6: June",
                                   "7: July",
                                   "8: August",
                                   "9: September",
                                   "10: October",
                                   "11: November",
                                   "12: December"))
  data$H0021400 <- factor(data$H0021400,
                          levels=c(0.0,1.0),
                          labels=c("NO",
                                   "YES"))
  ## maybe keep?
  #  data$R0144600[10.0 <= data$R0144600 & data$R0144600 <= 9999.0] <- 10.0
  #  data$R0144600[10010.0 <= data$R0144600 & data$R0144600 <= 10829.0] <- 10010.0
  #  data$R0144600[11800.0 <= data$R0144600 & data$R0144600 <= 11999.0] <- 11800.0
  #  data$R0144600[12800.0 <= data$R0144600 & data$R0144600 <= 12997.0] <- 12800.0
  # data$R0144600 <- factor(data$R0144600,
  #   levels=c(0.0,10.0,10010.0,11800.0,12800.0),
  #   labels=c("0: 0 NO HEALTH LIMITATION",
  #     "10 TO 9999: 0010 THRU  9999 ICD-9 HEALTH CODE",
  #     "10010 TO 10829: 10010 THRU 10829 ICD-9 'V' CODE",
  #     "11800 TO 11999: 11800 THRU 11999 ICD-9 'E' CODE",
  #      "12800 TO 12997: 12800 THRU 12997 ICD-9 'M' CODE"))
  data$R0173600 <- factor(data$R0173600,
                          levels=c(1.0,2.0,3.0,4.0,5.0,6.0,7.0,8.0,9.0,10.0,11.0,12.0,13.0,14.0,15.0,16.0,17.0,18.0,19.0,20.0),
                          labels=c("CROSS MALE WHITE",
                                   "CROSS MALE WH. POOR",
                                   "CROSS MALE BLACK",
                                   "CROSS MALE HISPANIC",
                                   "CROSS FEMALE WHITE",
                                   "CROSS FEMALE WH POOR",
                                   "CROSS FEMALE BLACK",
                                   "CROSS FEMALE HISPANIC",
                                   "SUP MALE WH POOR",
                                   "SUP MALE BLACK",
                                   "SUP MALE HISPANIC",
                                   "SUP FEM WH POOR",
                                   "SUP FEMALE BLACK",
                                   "SUP FEMALE HISPANIC",
                                   "MIL MALE WHITE",
                                   "MIL MALE BLACK",
                                   "MIL MALE HISPANIC",
                                   "MIL FEMALE WHITE",
                                   "MIL FEMALE BLACK",
                                   "MIL FEMALE HISPANIC"))
  data$R3894900 <- factor(data$R3894900,
                          levels=c(0.0,1.0,2.0,3.0),
                          labels=c("RARELY/NONE OF THE TIME/1 DAY",
                                   "SOME/A LITTLE OF THE TIME/1-2 DAYS",
                                   "OCCASIONALLY/MODERATE AMT OF THE TIME/3-4 DAYS",
                                   "MOST/ALL OF THE TIME/5-7 DAYS"))
  data$R3895000 <- factor(data$R3895000,
                          levels=c(0.0,1.0,2.0,3.0),
                          labels=c("RARELY/NONE OF THE TIME/1 DAY",
                                   "SOME/A LITTLE OF THE TIME/1-2 DAYS",
                                   "OCCASIONALLY/MODERATE AMT OF THE TIME/3-4 DAYS",
                                   "MOST/ALL OF THE TIME/5-7 DAYS"))
  data$R3895100 <- factor(data$R3895100,
                          levels=c(0.0,1.0,2.0,3.0),
                          labels=c("RARELY/NONE OF THE TIME/1 DAY",
                                   "SOME/A LITTLE OF THE TIME/1-2 DAYS",
                                   "OCCASIONALLY/MODERATE AMT OF THE TIME/3-4 DAYS",
                                   "MOST/ALL OF THE TIME/5-7 DAYS"))
  data$R3895200 <- factor(data$R3895200,
                          levels=c(0.0,1.0,2.0,3.0),
                          labels=c("RARELY/NONE OF THE TIME/1 DAY",
                                   "SOME/A LITTLE OF THE TIME/1-2 DAYS",
                                   "OCCASIONALLY/MODERATE AMT OF THE TIME/3-4 DAYS",
                                   "MOST/ALL OF THE TIME/5-7 DAYS"))
  data$R3895300 <- factor(data$R3895300,
                          levels=c(0.0,1.0,2.0,3.0),
                          labels=c("RARELY/NONE OF THE TIME/1 DAY",
                                   "SOME/A LITTLE OF THE TIME/1-2 DAYS",
                                   "OCCASIONALLY/MODERATE AMT OF THE TIME/3-4 DAYS",
                                   "MOST/ALL OF THE TIME/5-7 DAYS"))
  data$R3895400 <- factor(data$R3895400,
                          levels=c(0.0,1.0,2.0,3.0),
                          labels=c("RARELY/NONE OF THE TIME/1 DAY",
                                   "SOME/A LITTLE OF THE TIME/1-2 DAYS",
                                   "OCCASIONALLY/MODERATE AMT OF THE TIME/3-4 DAYS",
                                   "MOST/ALL OF THE TIME/5-7 DAYS"))
  data$R3895500 <- factor(data$R3895500,
                          levels=c(0.0,1.0,2.0,3.0),
                          labels=c("RARELY/NONE OF THE TIME/1 DAY",
                                   "SOME/A LITTLE OF THE TIME/1-2 DAYS",
                                   "OCCASIONALLY/MODERATE AMT OF THE TIME/3-4 DAYS",
                                   "MOST/ALL OF THE TIME/5-7 DAYS"))
  data$R3895600 <- factor(data$R3895600,
                          levels=c(0.0,1.0,2.0,3.0),
                          labels=c("RARELY/NONE OF THE TIME/1 DAY",
                                   "SOME/A LITTLE OF THE TIME/1-2 DAYS",
                                   "OCCASIONALLY/MODERATE AMT OF THE TIME/3-4 DAYS",
                                   "MOST/ALL OF THE TIME/5-7 DAYS"))
  data$R3895700 <- factor(data$R3895700,
                          levels=c(0.0,1.0,2.0,3.0),
                          labels=c("RARELY/NONE OF THE TIME/1 DAY",
                                   "SOME/A LITTLE OF THE TIME/1-2 DAYS",
                                   "OCCASIONALLY/MODERATE AMT OF THE TIME/3-4 DAYS",
                                   "MOST/ALL OF THE TIME/5-7 DAYS"))
  data$R3895800 <- factor(data$R3895800,
                          levels=c(0.0,1.0,2.0,3.0),
                          labels=c("RARELY/NONE OF THE TIME/1 DAY",
                                   "SOME/A LITTLE OF THE TIME/1-2 DAYS",
                                   "OCCASIONALLY/MODERATE AMT OF THE TIME/3-4 DAYS",
                                   "MOST/ALL OF THE TIME/5-7 DAYS"))
  data$R3895900 <- factor(data$R3895900,
                          levels=c(0.0,1.0,2.0,3.0),
                          labels=c("RARELY/NONE OF THE TIME/1 DAY",
                                   "SOME/A LITTLE OF THE TIME/1-2 DAYS",
                                   "OCCASIONALLY/MODERATE AMT OF THE TIME/3-4 DAYS",
                                   "MOST/ALL OF THE TIME/5-7 DAYS"))
  data$R3896000 <- factor(data$R3896000,
                          levels=c(0.0,1.0,2.0,3.0),
                          labels=c("RARELY/NONE OF THE TIME/1 DAY",
                                   "SOME/A LITTLE OF THE TIME/1-2 DAYS",
                                   "OCCASIONALLY/MODERATE AMT OF THE TIME/3-4 DAYS",
                                   "MOST/ALL OF THE TIME/5-7 DAYS"))
  data$R3896100 <- factor(data$R3896100,
                          levels=c(0.0,1.0,2.0,3.0),
                          labels=c("RARELY/NONE OF THE TIME/1 DAY",
                                   "SOME/A LITTLE OF THE TIME/1-2 DAYS",
                                   "OCCASIONALLY/MODERATE AMT OF THE TIME/3-4 DAYS",
                                   "MOST/ALL OF THE TIME/5-7 DAYS"))
  data$R3896200 <- factor(data$R3896200,
                          levels=c(0.0,1.0,2.0,3.0),
                          labels=c("RARELY/NONE OF THE TIME/1 DAY",
                                   "SOME/A LITTLE OF THE TIME/1-2 DAYS",
                                   "OCCASIONALLY/MODERATE AMT OF THE TIME/3-4 DAYS",
                                   "MOST/ALL OF THE TIME/5-7 DAYS"))
  data$R3896300 <- factor(data$R3896300,
                          levels=c(0.0,1.0,2.0,3.0),
                          labels=c("RARELY/NONE OF THE TIME/1 DAY",
                                   "SOME/A LITTLE OF THE TIME/1-2 DAYS",
                                   "OCCASIONALLY/MODERATE AMT OF THE TIME/3-4 DAYS",
                                   "MOST/ALL OF THE TIME/5-7 DAYS"))
  data$R3896400 <- factor(data$R3896400,
                          levels=c(0.0,1.0,2.0,3.0),
                          labels=c("RARELY/NONE OF THE TIME/1 DAY",
                                   "SOME/A LITTLE OF THE TIME/1-2 DAYS",
                                   "OCCASIONALLY/MODERATE AMT OF THE TIME/3-4 DAYS",
                                   "MOST/ALL OF THE TIME/5-7 DAYS"))
  data$R3896500 <- factor(data$R3896500,
                          levels=c(0.0,1.0,2.0,3.0),
                          labels=c("RARELY/NONE OF THE TIME/1 DAY",
                                   "SOME/A LITTLE OF THE TIME/1-2 DAYS",
                                   "OCCASIONALLY/MODERATE AMT OF THE TIME/3-4 DAYS",
                                   "MOST/ALL OF THE TIME/5-7 DAYS"))
  data$R3896600 <- factor(data$R3896600,
                          levels=c(0.0,1.0,2.0,3.0),
                          labels=c("RARELY/NONE OF THE TIME/1 DAY",
                                   "SOME/A LITTLE OF THE TIME/1-2 DAYS",
                                   "OCCASIONALLY/MODERATE AMT OF THE TIME/3-4 DAYS",
                                   "MOST/ALL OF THE TIME/5-7 DAYS"))
  data$R3896700 <- factor(data$R3896700,
                          levels=c(0.0,1.0,2.0,3.0),
                          labels=c("RARELY/NONE OF THE TIME/1 DAY",
                                   "SOME/A LITTLE OF THE TIME/1-2 DAYS",
                                   "OCCASIONALLY/MODERATE AMT OF THE TIME/3-4 DAYS",
                                   "MOST/ALL OF THE TIME/5-7 DAYS"))
  data$R3896800 <- factor(data$R3896800,
                          levels=c(0.0,1.0,2.0,3.0),
                          labels=c("RARELY/NONE OF THE TIME/1 DAY",
                                   "SOME/A LITTLE OF THE TIME/1-2 DAYS",
                                   "OCCASIONALLY/MODERATE AMT OF THE TIME/3-4 DAYS",
                                   "MOST/ALL OF THE TIME/5-7 DAYS"))
  data$R4978300 <- factor(data$R4978300,
                          levels=c(0.0,1.0,2.0,3.0),
                          labels=c("Rarely/None of the Time/1 Day",
                                   "Some/A Little of the Time/1-2 Days",
                                   "Occasionally/Moderate Amount of the Time/3-4 Days",
                                   "Most/All of the Time/5-7 Days"))
  data$R4978400 <- factor(data$R4978400,
                          levels=c(0.0,1.0,2.0,3.0),
                          labels=c("Rarely/None of the Time/1 Day",
                                   "Some/A Little of the Time/1-2 Days",
                                   "Occasionally/Moderate Amount of the Time/3-4 Days",
                                   "Most/All of the Time/5-7 Days"))
  data$R4978500 <- factor(data$R4978500,
                          levels=c(0.0,1.0,2.0,3.0),
                          labels=c("Rarely/None of the Time/1 Day",
                                   "Some/A Little of the Time/1-2 Days",
                                   "Occasionally/Moderate Amount of the Time/3-4 Days",
                                   "Most/All of the Time/5-7 Days"))
  data$R4978600 <- factor(data$R4978600,
                          levels=c(0.0,1.0,2.0,3.0),
                          labels=c("Rarely/None of the Time/1 Day",
                                   "Some/A Little of the Time/1-2 Days",
                                   "Occasionally/Moderate Amount of the Time/3-4 Days",
                                   "Most/All of the Time/5-7 Days"))
  data$R4978700 <- factor(data$R4978700,
                          levels=c(0.0,1.0,2.0,3.0),
                          labels=c("Rarely/None of the Time/1 Day",
                                   "Some/A Little of the Time/1-2 Days",
                                   "Occasionally/Moderate Amount of the Time/3-4 Days",
                                   "Most/All of the Time/5-7 Days"))
  data$R4978800 <- factor(data$R4978800,
                          levels=c(0.0,1.0,2.0,3.0),
                          labels=c("Rarely/None of the Time/1 Day",
                                   "Some/A Little of the Time/1-2 Days",
                                   "Occasionally/Moderate Amount of the Time/3-4 Days",
                                   "Most/All of the Time/5-7 Days"))
  data$R4978900 <- factor(data$R4978900,
                          levels=c(0.0,1.0,2.0,3.0),
                          labels=c("Rarely/None of the Time/1 Day",
                                   "Some/A Little of the Time/1-2 Days",
                                   "Occasionally/Moderate Amount of the Time/3-4 Days",
                                   "Most/All of the Time/5-7 Days"))

  data$T5006600 <- factor(data$T5006600,
                          levels=c(1.0,2.0,3.0,4.0,5.0,6.0,7.0),
                          labels=c("1 (not at all satisfied)",
                                   "2",
                                   "3",
                                   "4",
                                   "5",
                                   "6",
                                   "7 (completely satisfied)"))
  data$T5740700 <- factor(data$T5740700,
                          levels=c(1.0,2.0,3.0,4.0,5.0,6.0,7.0),
                          labels=c("1 (not at all satisfied)",
                                   "2",
                                   "3",
                                   "4",
                                   "5",
                                   "6",
                                   "7 (completely satisfied)"))
  return(data)
}
